name: morestrings
description: testing running go test via GitHub Action
runs:
  using: docker
  image: Dockerfile
  entrypoint: /bin/sh
  args:
    - "-c"
    - "mkdir -p output; (cd /usr/src/app && go test --json | jq -s) | tee output/test-output.json"
