name: morestrings
description: testing running go test via GitHub Action
runs:
  using: docker
  image: Dockerfile
  entrypoint: /bin/sh
  args:
    - "-c"
    - "go test --json | jq -s | tee test-output.json"
